### Create a new item
POST http://localhost:3000/items
Content-Type: application/json

{
  "name": "Sample Item3",
  "category": "Sample Category",
  "storePrices": [
    {
      "storeId": "67dbd57e1f125b07a443683b",
      "price": 19.99
    }
  ]
}

### Create a new store
POST http://localhost:3000/stores
Content-Type: application/json

{
  "name": "My Store"
}
### Get all items
GET http://localhost:3000/items

### Get item by ID
GET http://localhost:3000/items/item123

### Update item by ID
PUT http://localhost:3000/items/item123
Content-Type: application/json

{
  "name": "Updated Item Name",
  "category": "Updated Category",
  "storePrices": [
    {
      "storeId": "store123",
      "price": 29.99
    }
  ]
}

### Delete item by ID
DELETE http://localhost:3000/items/item123


### Create a new store
POST http://localhost:3000/stores
Content-Type: application/json

{
  "name": "My Store1"
  
}

### Get all stores
GET http://localhost:3000/stores

### Get store by ID
GET http://localhost:3000/stores/store1233

### Update store by ID
PUT http://localhost:3000/stores/store1233
Content-Type: application/json

{
  "name": "Updated Store Name"

}

### Delete store by ID
DELETE http://localhost:3000/stores/store123



###
# Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "user3@test.com",
  "password": "123456789",
  "userName": "user3",
  "accessToken": "12345",
  "profilePicture": "https://images.ctfassets.net/wv75stsetqy3/DaKdXY2tkQGWeVQiCbSx7/ac01166282697e4e0cafb99180d35cd1/Thailand_Featured.jpg?q=60&fit=fill&fm=webp"
}


###

# Login a user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "user3@test.com",
  "password": "123456789"
}

###

# Refresh Token
POST http://localhost:3000/auth/refresh
Authorization: Bearer your_refresh_token

###

# Logout a user
POST http://localhost:3000/auth/logout
Authorization: Bearer your_refresh_token

###

# Update user
PUT http://localhost:3000/auth/your_user_id
Content-Type: application/json
Authorization: Bearer your_access_token

{
  "email": "newemail@example.com",
  "password": "newpassword"
}

  
