### Create a new item
POST http://localhost:3000/items
Content-Type: application/json

{
  "name": "Itemmm",
  "category": "food",
  "image": "http://example.com/image.jpg",
  "code": "ITEM123",
  "storePrices": [
    {
      "storeId": "67dbd57e1f125b07a443683b",
      "prices": [
        {
          "date": "2025-03-20T08:22:21.735Z",
          "price": 19.99
        }
      ]
    }
  ]
}
### Get all items
GET http://localhost:3000/items

### Get item by ID
GET http://localhost:3000/items/item123

### Update item by ID
PUT http://localhost:3000/items/item123
Content-Type: application/json

{
  "name": "Updated Item Name",
  "category": "Updated Category",
  "storePrices": [
    {
      "storeId": "67dbd03da192adc18c40d4a0",  // Replace with a valid ObjectId
      "prices": [
        {
          "date": "2025-03-20T08:22:21.735Z",
          "price": 29.99
        }
      ]
    }
  ]
}

### Delete item by ID
DELETE http://localhost:3000/items/item123


### Create a new store
POST http://localhost:3000/stores
Content-Type: application/json

{
  "name": "My Store"
}

### Get all stores
GET http://localhost:3000/stores

### Get store by ID
GET http://localhost:3000/stores/67dbd03da192adc18c40d4a0

### Update store by ID
PUT http://localhost:3000/stores/67dbd03da192adc18c40d4a0
Content-Type: application/json

{
  "name": "Updated Store Name"
}

### Delete store by ID
DELETE http://localhost:3000/stores/67dbd03da192adc18c40d4a0


### Create a new item
POST http://localhost:3000/items
Content-Type: application/json

{
  "name": "Sample Item3",
  "category": "Sample Category",
  "storePrices": [
    {
      "storeId": "67dbd57e1f125b07a443683b",
      "price": 19.99
    }
  ]
}

### Create a new store
POST http://localhost:3000/stores
Content-Type: application/json

{
  "name": "My Store"
}
### Get all items
GET http://localhost:3000/items

### Get item by ID
GET http://localhost:3000/items/item123

### Update item by ID
PUT http://localhost:3000/items/item123
Content-Type: application/json

{
  "name": "Updated Item Name",
  "category": "Updated Category",
  "storePrices": [
    {
      "storeId": "store123",
      "price": 29.99
    }
  ]
}

### Delete item by ID
DELETE http://localhost:3000/items/item123


### Create a new store
POST http://localhost:3000/stores
Content-Type: application/json

{
  "name": "My Store1"
  
}

### Get all stores
GET http://localhost:3000/stores

### Get store by ID
GET http://localhost:3000/stores/store1233

### Update store by ID
PUT http://localhost:3000/stores/store1233
Content-Type: application/json

{
  "name": "Updated Store Name"

}

### Delete store by ID
DELETE http://localhost:3000/stores/store123



###
# Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "user16@test.com",
  "password": "123456789",
  "userName": "user16",
  "accessToken": "12345",
  "profilePicture": "https://images.ctfassets.net/wv75stsetqy3/DaKdXY2tkQGWeVQiCbSx7/ac01166282697e4e0cafb99180d35cd1/Thailand_Featured.jpg?q=60&fit=fill&fm=webp"
}


###

# Login a user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "user3@test.com",
  "password": "123456789"
}

###

# Refresh Token
POST http://localhost:3000/auth/refresh
Authorization: Bearer your_refresh_token

###

# Logout a user
POST http://localhost:3000/auth/logout
Authorization: Bearer your_refresh_token

###

# Update user
PUT http://localhost:3000/auth/your_user_id
Content-Type: application/json
Authorization: Bearer your_access_token

{
  "email": "newemail@example.com",
  "password": "newpassword"
}

  
### יצירת עגלה חדשה
POST http://localhost:3000/cart
Content-Type: application/json

{
  "name": "עגלה לחגים",
  "ownerId": "user16",
  "participants": ["user456", "user789"],
  "items": [
    { "productId": "milk123", "quantity": 2 },
    { "productId": "bread456", "quantity": 1 }
  ]
}

### שליפת כל העגלות של משתמש (כבעלים או משתתף)
GET http://localhost:3000/cart?userId=user16

### שליפת עגלה לפי מזהה
GET http://localhost:3000/cart/6804a224096351b9e364fa7e

### עדכון עגלה קיימת
PUT http://localhost:3000/cart/6804a224096351b9e364fa7e
Content-Type: application/json

{
  "name": "עגלה מעודכנת",
  "items": [
    { "productId": "milk123", "quantity": 3 },
    { "productId": "eggs789", "quantity": 2 }
  ]
}

### מחיקת עגלה
DELETE http://localhost:3000/cart/6804a224096351b9e364fa7e


###
GET http://localhost:3000/chat/123

{
  {
    "sender": "Coral",
    "message": "היי כולם",
    "timestamp": "2025-05-14T18:00:00.000Z"
  }
}